# Generated by Django 5.1.2 on 2025-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
