# Generated by Django 5.1.2 on 2025-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_jobposition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='job_position',
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CapturedData',
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
    ]
